version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    ports:
      - 3000:3000

networks:
  app_network:
    driver: bridge

volumes:
  nesjs: